---
# tasks file for valheim-server
- name: Add the user 'james' with a bash shell
  user:
    name: "{{ gm_name }}"
    shell: /bin/bash
    append: yes

- name: set install dir
  set_fact:
    install_dir: /home/{{ gm_name }}/valheim
  when: install_dir is not defined


- debug:
    var: ansible_architecture

- name: x86_64 fix
  block:


    - name: add multiver repository debian
      apt:
        name: lib32gcc-s1
        state: present
        update_cache: yes
      when:  ansible_os_family == 'Debian'

    # - name: install git for RedHat systems
    #   dnf: name=lib32gcc update_cache=yes
    #   when:  ansible_os_family == 'RedHat'

    # - name: install lib32gcc1
    #   package:
    #     name: steamcmd
    #     state: latest

  when: ansible_architecture == "x86_64"

- name: install screen
  become: yes
  become_user: root
  package:
    name: screen
    state: present

- block:
  - name: ensure main directory exists
    file:
      path: "{{ install_dir }}"
      state: directory

  - name: update steamcmd on first run
    shell:
      cmd: steamcmd
      chdir: "{{ install_dir }}"


  - name: install server files
    shell:
      cmd: "{{ install_dir }}/linux32/steamcmd +login anonymous +force_install_dir {{ install_dir }} +app_update 896660 validate +exit"
      chdir: "{{ install_dir }}"

  - name: run valheim
    shell:
      cmd: screen -d -m ./start_server.sh
      chdir: "{{ install_dir }}"
  become_user: "{{ gm_name }}"
