---
# tasks file for valheim-server
- name: Add the user with a bash shell
  user:
    name: "{{ gm_name }}"
    shell: /bin/bash
    append: yes

- name: set user password
  user:
    name: "{{ gm_name }}"
    shell: /bin/bash
    password: "{{ gm_pass }}"
    append: yes
  when: gm_pass is defined

- name: Set authorized key
  authorized_key:
    user: "{{ gm_name }}"
    state: present
    key: "{{ gm_ssh_key }}"
  when: gm_ssh_key is defined

- name: set install dir
  set_fact:
    install_dir: /home/{{ gm_name }}/valheim
  when: install_dir is not defined

- name: install screen
  become: yes
  become_user: root
  package:
    name: screen
    state: present

- block:
  - name: install steamcmd
    import_role:
      name: ansible-steamcmd
    vars:
      steamcmd_user: "{{ gm_name }}"

  - name: ensure main directory exists
    file:
      path: "{{ install_dir }}"
      state: directory
      owner: "{{ gm_name }}"
      group: "{{ gm_name }}"
      mode: '0644'

  - name: install server files
    shell:
      cmd: "/usr/games/steamcmd +login anonymous +force_install_dir {{ install_dir }} +app_update 896660 validate +exit"
      chdir: "{{ install_dir }}"

  - name: "generate start_server.sh script"
    template:
      src: templates/start_server.j2
      dest: "{{ install_dir }}/start_server.sh"
      owner: "{{ gm_name }}"
      group: "{{ gm_name }}"
      mode: '0644'

  - name: run valheim
    shell:
      cmd: screen -d -m ./start_server.sh
      chdir: "{{ install_dir }}"
    when: run_valheim
  become_user: "{{ gm_name }}"
