---
dependency:
  name: galaxy
  requirements-file: requirement.yml
driver:
  name: docker
platforms:
  - name: debian
    image: docker.io/pycontribs/debian:latest
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
